### ISSUE TITLE
problems running fetcher on current main branch

### ISSUE THREAD

**Issue by philbudne** [mediacloud/story-indexer#175]
This is from running deploy.sh on main branch (deploying dev stack pbudne-indexer) on ifill

@pgulley I see `AttributeError: module 'indexer.workers.fetcher' has no attribute 'BlacklistRedirectMiddleware'` -- could it be related to your recent merge?

```
ELASTICSEARCH_INDEX_NAME_PREFIX=mediacloud_search_text
APP_HOST=.
LOG_LEVEL=info
HOSTNAME=8d375f7cb87a
PYTHON_PIP_VERSION=23.0.1
APP_DOCKER=/app
HOME=/root
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
ARGS=--yesterday --sample-size=5000 --num-batches=10 --batch-index=1
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/4cfa4081d27285bda1220a62a5ebf5b4bd749cdb/public/get-pip.py
ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RABBITMQ_URL=amqp://rabbitmq:5672/?connection_attempts=10&retry_delay=5
LANG=C.UTF-8
STATSD_URL=statsd://stats.tarbell.mediacloud.org
PYTHON_VERSION=3.10.13
PYTHON_SETUPTOOLS_VERSION=65.5.1
SENTRY_ENVIRONMENT=disabled_by_empty_dsn
PWD=/app
PYTHON_GET_PIP_SHA256=9cc01665956d22b3bf057ae8287b035827bfd895da235bcea200ab3b811790b6
RUN=fetcher
STATSD_REALM=pbudne
STORY_FACTORY=BaseStory
TZ=GMT
log: -t run-fetcher.sh -p debug invoking indexer.workers.fetcher.fetch_worker --yesterday --sample-size=5000 --num-batches=10 --batch-index=1
2023-12-03 01:15:45,115 | INFO | __main__ | Namespace(log_level=None, list_loggers=False, logger_level=None, amqp_url='amqp://rabbitmq:5672/?connection_attempts=10&retry_delay=5', from_quarantine=False, yesterday=True, fetch_date=None, num_batches=10, batch_index=1, sample_size=5000)
2023-12-03 01:15:45,115 | INFO | __main__ | Fetching for yesterday
2023-12-03 01:15:45,115 | INFO | indexer.app | sending stats to statsd://stats.tarbell.mediacloud.org prefix mc.pbudne.story-indexer.fetcher
2023-12-03 01:15:45,115 | INFO | __main__ | Fetching rss batch 0 for 2023-12-01
2023-12-03 01:17:39,019 | INFO | __main__ | Batch 0:  5 stories, from 246 domains (~0.02032520325203252 stories per domain
2023-12-03 01:17:39,019 | INFO | __main__ | Batch 1:  5 stories, from 249 domains (~0.020080321285140562 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Batch 2:  5 stories, from 249 domains (~0.020080321285140562 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Batch 3:  5 stories, from 249 domains (~0.020080321285140562 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Batch 4:  5 stories, from 250 domains (~0.02 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Batch 5:  5 stories, from 251 domains (~0.0199203187250996 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Batch 6:  5 stories, from 252 domains (~0.01984126984126984 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Batch 7:  5 stories, from 252 domains (~0.01984126984126984 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Batch 8:  5 stories, from 252 domains (~0.01984126984126984 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Batch 9:  5 stories, from 252 domains (~0.01984126984126984 stories per domain
2023-12-03 01:17:39,020 | INFO | __main__ | Initializing stories for 0 on 2023-12-01
2023-12-03 01:17:39,091 | INFO | __main__ | Initialized 500 stories
2023-12-03 01:17:39,098 | INFO | scrapy.utils.log | Scrapy 2.10.1 started (bot: scrapybot)
2023-12-03 01:17:39,101 | INFO | scrapy.utils.log | Versions: lxml 4.9.3.0, libxml2 2.10.3, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 22.10.0, Python 3.10.13 (main, Nov 29 2023, 05:26:45) [GCC 12.2.0], pyOpenSSL 23.3.0 (OpenSSL 3.1.4 24 Oct 2023), cryptography 41.0.5, Platform Linux-5.15.0-84-generic-x86_64-with-glibc2.36
2023-12-03 01:17:39,101 | INFO | __main__ | Launching Batch Spider Process for Batch 0
2023-12-03 01:17:39,104 | INFO | scrapy.addons | Enabled addons:
[]
2023-12-03 01:17:39,105 | INFO | scrapy.crawler | Overridden settings:
 'AUTOTHROTTLE_ENABLED': True,
 'AUTOTHROTTLE_TARGET_CONCURRENCY': 10,
 'CONCURRENT_REQUESTS_PER_DOMAIN': 2,
 'COOKIES_ENABLED': False,
 'DOWNLOAD_TIMEOUT': 60,
 'RETRY_HTTP_CODES': [502, 503, 504, 522, 524, 408, 429],
 'USER_AGENT': 'mediacloud bot for open academic research '
               '(+https://mediacloud.org)'}
2023-12-03 01:17:39,106 | WARNING | py.warnings | /usr/local/lib/python3.10/site-packages/scrapy/utils/request.py:248: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)
2023-12-03 01:17:39,123 | INFO | scrapy.extensions.telnet | Telnet Password: 0a021a5b5cdd22ff
2023-12-03 01:17:39,273 | INFO | scrapy.middleware | Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.throttle.AutoThrottle']
2023-12-03 01:17:39,303 | INFO | __main__ | Fetched 0 stories in batch 0
2023-12-03 01:17:39,303 | INFO | indexer.worker | waiting until queues configured....
2023-12-03 01:17:39,319 | INFO | indexer.worker | queues configured
2023-12-03 01:17:39,323 | INFO | pika.adapters.utils.connection_workflow | Pika version 1.3.2 connecting to ('10.0.39.6', 5672)
2023-12-03 01:17:39,324 | INFO | pika.adapters.utils.io_services_utils | Socket connected: <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.39.112', 50618), raddr=('10.0.39.6', 5672)>
2023-12-03 01:17:39,327 | INFO | pika.adapters.utils.connection_workflow | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa102ef1f60>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa102ef1f60> params=<URLParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
2023-12-03 01:17:39,333 | INFO | pika.adapters.utils.connection_workflow | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa102ef1f60> params=<URLParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2023-12-03 01:17:39,334 | INFO | pika.adapters.utils.connection_workflow | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa102ef1f60> params=<URLParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2023-12-03 01:17:39,334 | INFO | pika.adapters.blocking_connection | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa102ef1f60> params=<URLParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2023-12-03 01:17:39,334 | INFO | indexer.worker | connected to amqp://rabbitmq:5672/?connection_attempts=10&retry_delay=5
2023-12-03 01:17:39,336 | INFO | pika.adapters.blocking_connection | Created channel=1
Unhandled error in Deferred:
2023-12-03 01:17:39,388 | CRITICAL | twisted | Unhandled error in Deferred:
2023-12-03 01:17:39 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 245, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 249, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1947, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1857, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 134, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 148, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/engine.py", line 98, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/downloader/__init__.py", line 97, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/middleware.py", line 67, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/middleware.py", line 43, in from_settings
    mwcls = load_object(clspath)
  File "/usr/local/lib/python3.10/site-packages/scrapy/utils/misc.py", line 84, in load_object
    raise NameError(f"Module '{module}' doesn't define any object named '{name}'")
builtins.NameError: Module 'indexer.workers.fetcher' doesn't define any object named 'BlacklistRedirectMiddleware'

2023-12-03 01:17:39,389 | CRITICAL | twisted | 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/scrapy/utils/misc.py", line 82, in load_object
    obj = getattr(mod, name)
AttributeError: module 'indexer.workers.fetcher' has no attribute 'BlacklistRedirectMiddleware'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 134, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 148, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/engine.py", line 98, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/downloader/__init__.py", line 97, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/middleware.py", line 67, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/middleware.py", line 43, in from_settings
    mwcls = load_object(clspath)
  File "/usr/local/lib/python3.10/site-packages/scrapy/utils/misc.py", line 84, in load_object
    raise NameError(f"Module '{module}' doesn't define any object named '{name}'")
NameError: Module 'indexer.workers.fetcher' doesn't define any object named 'BlacklistRedirectMiddleware'
2023-12-03 01:17:39 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/scrapy/utils/misc.py", line 82, in load_object
    obj = getattr(mod, name)
AttributeError: module 'indexer.workers.fetcher' has no attribute 'BlacklistRedirectMiddleware'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 134, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 148, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/engine.py", line 98, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/downloader/__init__.py", line 97, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/middleware.py", line 67, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.10/site-packages/scrapy/middleware.py", line 43, in from_settings
    mwcls = load_object(clspath)
  File "/usr/local/lib/python3.10/site-packages/scrapy/utils/misc.py", line 84, in load_object
    raise NameError(f"Module '{module}' doesn't define any object named '{name}'")
NameError: Module 'indexer.workers.fetcher' doesn't define any object named 'BlacklistRedirectMiddleware'
log: -t run-fetcher.sh -p debug indexer.workers.fetcher.fetch_worker --yesterday --sample-size=5000 --num-batches=10 --batch-index=1 exit status 0
log: -t bin/run-fetcher.sh -p info bin/run-fetcher.sh --yesterday --sample-size=5000 --num-batches=10 --batch-index=1 exit status 0
```

**Comment by philbudne** [comment]
Any progress?

**Comment by pgulley** [comment]
#183 addresses this!
