### ISSUE TITLE
Error while fetching server API version: Not supported URL scheme http+docker

### ISSUE THREAD

**Issue by pgulley** [mediacloud/story-indexer#317]
This error makes up a bulk of our Sentry error capacity- we see it about 33k times a day. Originating [here](https://github.com/mediacloud/story-indexer/blob/bcf19423aac12ebd8367285c2d9af3eb541fd004/indexer/scripts/docker-stats.py#L52). I take it this is an inconsequential error, since we are successfully collecting stats- what intervention is needed?

**Comment by philbudne** [comment]
I will investigate.

**Comment by philbudne** [comment]
From a staging-rss-indexer stack on posey; I've removed the stack @thepsalmist 

```
root@posey:/nfs/ang/users/pbudne# docker logs 05a884836c6c
APP_HOST=.
LOG_LEVEL=info
HOSTNAME=05a884836c6c
PYTHON_PIP_VERSION=23.0.1
SYSLOG_PORT=5140
APP_DOCKER=/app
HOME=/root
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
ARGS=--stack staging-rss-indexer
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/e03e1607ad60522cf34a92e834138eb89f57667c/public/get-pip.py
ELASTICSEARCH_HOSTS=http://elasticsearch1:9200,http://elasticsearch2:9200,http://elasticsearch3:9200
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RABBITMQ_URL=amqp://rabbitmq:5672/?connection_attempts=10&retry_delay=5
ELASTICSEARCH_CONFIG_DIR=./conf/elasticsearch/templates
LANG=C.UTF-8
DEPLOYMENT_ID=mc-configuration-2024-07-24-06-34-23-staging-rss-indexer
STATSD_URL=statsd://stats.tarbell.mediacloud.org
PYTHON_VERSION=3.10.14
PYTHON_SETUPTOOLS_VERSION=65.5.1
SENTRY_DSN=https://ea52554213726f8720ec36e933c74433@o33894.ingest.sentry.io/4506343417315328
SENTRY_ENVIRONMENT=staging
PWD=/app
PYTHON_GET_PIP_SHA256=ee09098395e42eb1f82ef4acb231a767a6ae85504a9cf9983223df0a7cbd35d7
RUN=docker-stats
STATSD_REALM=rss-staging
STORY_FACTORY=BaseStory
TZ=GMT
SYSLOG_HOST=syslog-sink
log: -t run-docker-stats.sh -p debug invoking indexer.scripts.docker-stats --stack staging-rss-indexer
2024-07-24 20:40:17,894 | INFO | indexer.app | sending stats to statsd://stats.tarbell.mediacloud.org prefix mc.rss-staging.story-indexer.docker-stats
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 633, in send
    conn = self.get_connection_with_tls_context(
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in get_connection_with_tls_context
    conn = self.poolmanager.connection_from_host(
  File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 325, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 637, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Not supported URL scheme http+docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/indexer/scripts/docker-stats.py", line 75, in <module>
    app.main()
  File "/app/indexer/app.py", line 404, in main
    self.main_loop()
  File "/app/indexer/scripts/docker-stats.py", line 52, in main_loop
    client = docker.client.from_env()
  File "/usr/local/lib/python3.10/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/usr/local/lib/python3.10/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
log: -t run-docker-stats.sh -p debug indexer.scripts.docker-stats --stack staging-rss-indexer exit status 1
log: -t bin/run-docker-stats.sh -p info bin/run-docker-stats.sh --stack staging-rss-indexer exit status 1
```

**Comment by philbudne** [comment]
Also from staging-hist stack and production hist stacks on bernstein.
I've removed the staging-hist stack @thepsalmist 
For the hist-indexer stack on bernstein I did `docker service scale hist-indexer_docker-stats=0`

**Comment by pgulley** [comment]
The stream of this error has run dry in sentry in the last 20 minutes- so I'll call this resolved!
